### ISSUE TITLE
Event "DrawBlockHighlightEvent" failed to load on start up

### ISSUE THREAD

**Issue by Blanketeer-X** [Naxanria/WTBW#2]
Simply put, that's what it does when I load it up with **forge-1.15.1-30.0.11**, even with the mod by itself. With that said, I'm assuming it's because of the mod being in 1.15, and not in 1.15.1? I'm just used to the previous versions not giving a care if it's 4 subversions behind the current one.

[2019-12-20-2.log](https://github.com/Naxanria/WTBW/files/3990595/2019-12-20-2.log)

**Comment by Naxanria** [comment]
Looks like they changed the event in that version. Will be fixed once we update to that version

**Comment by Naxanria** [comment]
Fixed in 1.15.1-1.0.2
